### ISSUE TITLE
can't write to a nfc tag of type NTAG203.

### ISSUE THREAD

**Issue by Tullemeck** [nfd/KeePassNFC#8]
![Uploading tmp_2765-type of nfc tag734521903.png…]()

**Comment by Tullemeck** [comment]
Finally able to write to tag
G!��`�}���Z��6+ 1st try

󍟅�������o�. 2nd try

2vpAuTEu+5euYe18 actual password
Keypassdroid can't seem to recieve proper password
When using Nfc tools the 2 upper is the string i get copyin to clipboard
Phone used: HTC obe (m7)
Country : sweden

**Comment by nfd** [comment]
Hi, sorry you're having trouble with KPNFC.

The tag doesn't store the password, just the decryption key, which is random bytes -- so the values you're reading from the tag using nfc tools aren't necessarily wrong (if you're just using it to read the value stored on the tag).

If you could answer some or all of the following it would be helpful:

1) Does KPNFC work with other NFC tags (if you have any, preferably different types)?
2) Does changing the password on the database (to something simple) make a difference?

Thanks

**Comment by Tullemeck** [comment]
Used http://www.1mobile.com/nfc-tools-2001825.html to erase nfc tag and triad agan
 Problem solved and database keepassdroid opened 
Issue marked as solved

**Comment by nfd** [comment]
Interesting. That seems like something KPNFC should do. Thanks for the report.
